### ISSUE TITLE
要是能在Mac运行就好了

### ISSUE THREAD

**Issue by m358807551** [chaoxiaodi/pytodolist#1]
看起来只能在Windows下运行，要是有个网页版就更好了。

**Comment by chaoxiaodi** [comment]
写了vue的网页版，可以直接访问，
https://blog.chaoxiaodi.tech/tools/todolist.html

不过mac的safari浏览器访问有问题，推荐使用chrome

或者克隆仓库
https://github.com/chaoxiaodi/vuetodolist
